/**
 * Created by wanpeng on 2017/8/14.
 */
export const FETCH_USERINFO = 'FETCH_USERINFO'
export const REQUEST_SMSCODE = 'REQUEST_SMSCODE'
export const SUBMIT_REGISTER = 'SUBMIT_REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_OUT = 'LOGIN_OUT'
export const AUTO_LOGIN = 'AUTO_LOGIN'
export const LOGIN = 'LOGIN'
export const REQUEST_VERIFY_IDNAME = 'REQUEST_VERIFY_IDNAME'
export const SAVE_IDNAME_INFO = 'SAVE_IDNAME_INFO'
export const AUTO_LOGIN_SUCCESS = 'AUTO_LOGIN_SUCCESS'

export const CREATE_PAYMENT = 'CREATE_PAYMENT'
export const CREATE_TRANSFER = 'CREATE_TRANSFER'

export const FETCH_WALLET_INFO = 'FETCH_WALLET_INFO'
export const FETCH_WALLET_INFO_SUCCESS = 'FETCH_WALLET_INFO_SUCCESS'
export const FETCH_DEAL_RECORDS = 'FETCH_DEAL_RECORDS'
export const FETCH_DEAL_RECORDS_SUCCESS = 'FETCH_DEAL_RECORDS_SUCCESS'

export const FETCH_WECHAT_JSSDK_CONFIG = 'FETCH_WECHAT_JSSDK_CONFIG'

