/**
 * Created by wanpeng on 2017/8/14.
 */
export const FETCH_USERINFO = 'FETCH_USERINFO'
export const FETCH_USERINFO_SCCESS = "FETCH_USERINFO_SCCESS"

export const REQUEST_SMSCODE = 'REQUEST_SMSCODE'
export const SUBMIT_REGISTER = 'SUBMIT_REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_OUT = 'LOGIN_OUT'
export const AUTO_LOGIN = 'AUTO_LOGIN'
export const LOGIN = 'LOGIN'

export const CREATE_PAYMENT = 'CREATE_PAYMENT'

export const FETCH_ORDER_INFO = 'FETCH_ORDER_INFO'
export const SAVE_ORDER_INFO = 'SAVE_ORDER_INFO'
