/**
 * Created by wanpeng on 2017/8/14.
 */
export const FETCH_WECHAT_USERINFO = 'FETCH_WECHAT_USERINFO'
export const FETCH_WECHAT_USERINFO_SCCESS = "FETCH_WECHAT_USERINFO_SCCESS"

export const REQUEST_SMSCODE = 'REQUEST_SMSCODE'
export const SUBMIT_REGISTER = 'SUBMIT_REGISTER'