/**
 * Created by yangyang on 2017/6/28.
 */
export const FETCH_DOMAIN = 'FETCH_DOMAIN'
export const FETCH_DOMAIN_SUCCESS = 'FETCH_DOMAIN_SUCCESS'
export const FETCH_POSITION = 'FETCH_POSITION'
export const FETCH_POSITION_SUCCESS = 'FETCH_POSITION_SUCCESS'