/**
 * Created by yangyang on 2017/6/28.
 */
export const FETCH_DOMAIN = 'FETCH_DOMAIN'
export const FETCH_DOMAIN_SUCCESS = 'FETCH_DOMAIN_SUCCESS'
export const FETCH_POSITION = 'FETCH_POSITION'
export const FETCH_POSITION_SUCCESS = 'FETCH_POSITION_SUCCESS'
export const UPDATE_REHYDRATE = 'UPDATE_REHYDRATE'
export const UPDATE_REHYDRATE_SUCCESS = 'UPDATE_REHYDRATE_SUCCESS'

export const UPDATE_INIT_URL = 'UPDATE_INIT_URL'
export const UPDATE_INIT_URL_SUCCESS = 'UPDATE_INIT_URL_SUCCESS'