/**
 * Created by wanpeng on 2017/9/29.
 */
export const FETCH_ORDERS = 'FETCH_ORDERS'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const PAYMENT_ORDER = 'PAYMENT_ORDER'
export const PAYMENT_ORDER_SUCCESS = 'PAYMENT_ORDER_SUCCESS'
export const UPDATE_ORDER = 'UPDATE_ORDER'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'