/**
 * Created by wanpeng on 2017/10/20.
 */
export const SAVE_PROMOTION = 'SAVE_PROMOTION'
export const SAVE_PROMOTIONS = 'SAVE_PROMOTIONS'
export const FETCH_PROMOTION = 'FETCH_PROMOTION'
export const UPDATE_PROMOTION_LIST = 'UPDATE_PROMOTION_LIST'
export const SAVE_PROMOTION_CATEGORY = 'SAVE_PROMOTION_CATEGORY'
export const SAVE_PROMOTION_CATEGORIES = 'SAVE_PROMOTION_CATEGORIES'
export const FETCH_PROMOTION_CATEGORYLIST = 'FETCH_PROMOTION_CATEGORYLIST'